# Generated by Django 4.2.23 on 2025-07-25 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabloom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='audio_url',
        ),
        migrations.AddField(
            model_name='word',
            name='audio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
